version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-backend
      - Health-Education-England/internal-admin-devops
